// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCpyFQ70C7b9HFJTRX-zsXUSG1HNFiqL4',
    appId: '1:14636580654:web:369ed919f7c15c5127c4bf',
    messagingSenderId: '14636580654',
    projectId: 'chatter-planet',
    authDomain: 'chatter-planet.firebaseapp.com',
    storageBucket: 'chatter-planet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8BkYPDyG6VcKTRUH3aYRgM3qZzUOwazw',
    appId: '1:14636580654:android:3aea10c9e96e54e327c4bf',
    messagingSenderId: '14636580654',
    projectId: 'chatter-planet',
    storageBucket: 'chatter-planet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZMRAjdDlcTqRmkdoNoQRbLx8-kliM4V4',
    appId: '1:14636580654:ios:d2b77dcd0a2ef2db27c4bf',
    messagingSenderId: '14636580654',
    projectId: 'chatter-planet',
    storageBucket: 'chatter-planet.appspot.com',
    iosBundleId: 'com.example.chatterPlanetApplication',
  );
}
